# telegram_data_dbt/models/sources.yml
version: 2

sources:
  - name: raw
    database: "{{ env_var('POSTGRES_DB') }}"
    schema: raw
    tables:
      - name: telegram_messages
        description: "Raw messages scraped from Telegram channels, stored as JSONB."
        columns:
          - name: id
            description: "Primary key for the raw message record."
            tests:
              - unique
              - not_null
          - name: channel_name
            description: "Name of the Telegram channel."
            tests:
              - not_null
          - name: message_date
            description: "Date the message was scraped."
            tests:
              - not_null
          - name: message_json
            description: "Full raw JSON object of the Telegram message."
            tests:
              - not_null
      - name: image_detections
        description: "Raw object detection results from YOLOv8."
        columns:
          - name: id
            description: "Primary key for the raw detection record."
            tests:
              - unique
              - not_null
          - name: image_path
            description: "Full path to the detected image file."
            tests:
              - not_null
          - name: detected_class
            description: "Class name of the detected object (e.g., 'person', 'car', 'pill')."
            tests:
              - not_null
          - name: confidence_score
            description: "Confidence score of the detection (0-1)."
            tests:
              - not_null
              - dbt_utils.at_least_one:
                  where: "confidence_score < 0 OR confidence_score > 1"
                  severity: error 